
// This file has been generated by the GUI designer. Do not modify.
namespace MultiPerceptron
{
	public partial class ConfigDialog
	{
		private global::Gtk.VBox vbox8;

		private global::Gtk.Label labelTitle;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Frame frame4;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.Table table2;

		private global::Gtk.ComboBox comboActivFunc;

		private global::Gtk.Entry entryName;

		private global::Gtk.Label label19;

		private global::Gtk.Label label20;

		private global::Gtk.Label label21;

		private global::Gtk.Label label22;

		private global::Gtk.Label label23;

		private global::Gtk.Label label32;

		private global::Gtk.SpinButton spinHidden;

		private global::Gtk.SpinButton spinInput;

		private global::Gtk.SpinButton spinLayers;

		private global::Gtk.SpinButton spinOutput;

		private global::Gtk.Label GtkLabel2;

		private global::Gtk.VBox vbox9;

		private global::Gtk.Frame frame5;

		private global::Gtk.Alignment GtkAlignment3;

		private global::Gtk.Table table3;

		private global::Gtk.Entry entryA;

		private global::Gtk.Entry entryB;

		private global::Gtk.Label label33;

		private global::Gtk.Label label34;

		private global::Gtk.Label labelFunc;

		private global::Gtk.Frame frame7;

		private global::Gtk.Alignment GtkAlignment5;

		private global::Gtk.VBox vbox10;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Button button16;

		private global::Gtk.Entry entryFile;

		private global::Gtk.CheckButton checkCorrel;

		private global::Gtk.CheckButton checkWhite;

		private global::Gtk.Label GtkLabel4;

		private global::Gtk.Frame frame6;

		private global::Gtk.Alignment GtkAlignment4;

		private global::Gtk.Table table4;

		private global::Gtk.HScale hscaleConstrain;

		private global::Gtk.HScale hscaleCrossRatio;

		private global::Gtk.HScale hscaleDropOut;

		private global::Gtk.HScale hscaleLearnRate;

		private global::Gtk.HScale hscaleMomentum;

		private global::Gtk.HScale hscaleRegular;

		private global::Gtk.HScale hscaleSmartScale;

		private global::Gtk.HScale hscaleStopDW;

		private global::Gtk.Label label24;

		private global::Gtk.Label label25;

		private global::Gtk.Label label26;

		private global::Gtk.Label label27;

		private global::Gtk.Label label28;

		private global::Gtk.Label label29;

		private global::Gtk.Label label30;

		private global::Gtk.Label label31;

		private global::Gtk.Label GtkLabel3;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget MultiPerceptron.ConfigDialog
			this.Name = "MultiPerceptron.ConfigDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child MultiPerceptron.ConfigDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 48;
			// Container child vbox8.Gtk.Box+BoxChild
			this.labelTitle = new global::Gtk.Label();
			this.labelTitle.Name = "labelTitle";
			this.labelTitle.LabelProp = global::Mono.Unix.Catalog.GetString("Perceptron Configurations");
			this.vbox8.Add(this.labelTitle);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.labelTitle]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 48;
			// Container child hbox9.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table(((uint)(6)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.comboActivFunc = global::Gtk.ComboBox.NewText();
			this.comboActivFunc.AppendText(global::Mono.Unix.Catalog.GetString("Sigm: a/(1+e^(-b·x))"));
			this.comboActivFunc.AppendText(global::Mono.Unix.Catalog.GetString("Tanh: a·tanh(b·x)"));
			this.comboActivFunc.AppendText(global::Mono.Unix.Catalog.GetString("ReLU: a·x, b·x"));
			this.comboActivFunc.AppendText(global::Mono.Unix.Catalog.GetString("ELU:  a·(e^x-1), b·x"));
			this.comboActivFunc.Name = "comboActivFunc";
			this.comboActivFunc.Active = 1;
			this.table2.Add(this.comboActivFunc);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2[this.comboActivFunc]));
			w3.TopAttach = ((uint)(5));
			w3.BottomAttach = ((uint)(6));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entryName = new global::Gtk.Entry();
			this.entryName.CanFocus = true;
			this.entryName.Name = "entryName";
			this.entryName.Text = global::Mono.Unix.Catalog.GetString("Unnamed");
			this.entryName.IsEditable = true;
			this.entryName.InvisibleChar = '●';
			this.table2.Add(this.entryName);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2[this.entryName]));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label19 = new global::Gtk.Label();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("Activ. function:");
			this.label19.Justify = ((global::Gtk.Justification)(1));
			this.table2.Add(this.label19);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2[this.label19]));
			w5.TopAttach = ((uint)(5));
			w5.BottomAttach = ((uint)(6));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label20 = new global::Gtk.Label();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("Output dimension:");
			this.label20.Justify = ((global::Gtk.Justification)(1));
			this.table2.Add(this.label20);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2[this.label20]));
			w6.TopAttach = ((uint)(4));
			w6.BottomAttach = ((uint)(5));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label21 = new global::Gtk.Label();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("Hidden dimension:");
			this.label21.Justify = ((global::Gtk.Justification)(1));
			this.table2.Add(this.label21);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2[this.label21]));
			w7.TopAttach = ((uint)(3));
			w7.BottomAttach = ((uint)(4));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label22 = new global::Gtk.Label();
			this.label22.Name = "label22";
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("Input dimension:");
			this.label22.Justify = ((global::Gtk.Justification)(1));
			this.table2.Add(this.label22);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2[this.label22]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label23 = new global::Gtk.Label();
			this.label23.Name = "label23";
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("Name:");
			this.label23.Justify = ((global::Gtk.Justification)(1));
			this.table2.Add(this.label23);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2[this.label23]));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label32 = new global::Gtk.Label();
			this.label32.Name = "label32";
			this.label32.LabelProp = global::Mono.Unix.Catalog.GetString("Hidden layers:");
			this.label32.Justify = ((global::Gtk.Justification)(1));
			this.table2.Add(this.label32);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2[this.label32]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.spinHidden = new global::Gtk.SpinButton(2D, 12D, 1D);
			this.spinHidden.CanFocus = true;
			this.spinHidden.Name = "spinHidden";
			this.spinHidden.Adjustment.PageIncrement = 10D;
			this.spinHidden.ClimbRate = 1D;
			this.spinHidden.Numeric = true;
			this.spinHidden.Value = 2D;
			this.table2.Add(this.spinHidden);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2[this.spinHidden]));
			w11.TopAttach = ((uint)(3));
			w11.BottomAttach = ((uint)(4));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.spinInput = new global::Gtk.SpinButton(2D, 12D, 1D);
			this.spinInput.CanFocus = true;
			this.spinInput.Name = "spinInput";
			this.spinInput.Adjustment.PageIncrement = 10D;
			this.spinInput.ClimbRate = 1D;
			this.spinInput.Numeric = true;
			this.spinInput.Value = 2D;
			this.table2.Add(this.spinInput);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2[this.spinInput]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.spinLayers = new global::Gtk.SpinButton(0D, 12D, 1D);
			this.spinLayers.CanFocus = true;
			this.spinLayers.Name = "spinLayers";
			this.spinLayers.Adjustment.PageIncrement = 10D;
			this.spinLayers.ClimbRate = 1D;
			this.spinLayers.Numeric = true;
			this.spinLayers.Value = 1D;
			this.table2.Add(this.spinLayers);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2[this.spinLayers]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.spinOutput = new global::Gtk.SpinButton(2D, 12D, 1D);
			this.spinOutput.CanFocus = true;
			this.spinOutput.Name = "spinOutput";
			this.spinOutput.Adjustment.PageIncrement = 10D;
			this.spinOutput.ClimbRate = 1D;
			this.spinOutput.Numeric = true;
			this.spinOutput.Value = 2D;
			this.table2.Add(this.spinOutput);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2[this.spinOutput]));
			w14.TopAttach = ((uint)(4));
			w14.BottomAttach = ((uint)(5));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment2.Add(this.table2);
			this.frame4.Add(this.GtkAlignment2);
			this.GtkLabel2 = new global::Gtk.Label();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Common</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame4.LabelWidget = this.GtkLabel2;
			this.hbox9.Add(this.frame4);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.frame4]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 24;
			// Container child vbox9.Gtk.Box+BoxChild
			this.frame5 = new global::Gtk.Frame();
			this.frame5.Name = "frame5";
			this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame5.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.table3 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.entryA = new global::Gtk.Entry();
			this.entryA.CanFocus = true;
			this.entryA.Name = "entryA";
			this.entryA.Text = global::Mono.Unix.Catalog.GetString("1.0");
			this.entryA.IsEditable = true;
			this.entryA.InvisibleChar = '●';
			this.table3.Add(this.entryA);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table3[this.entryA]));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryB = new global::Gtk.Entry();
			this.entryB.CanFocus = true;
			this.entryB.Name = "entryB";
			this.entryB.Text = global::Mono.Unix.Catalog.GetString("1.0");
			this.entryB.IsEditable = true;
			this.entryB.InvisibleChar = '●';
			this.table3.Add(this.entryB);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table3[this.entryB]));
			w19.TopAttach = ((uint)(1));
			w19.BottomAttach = ((uint)(2));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label33 = new global::Gtk.Label();
			this.label33.Name = "label33";
			this.label33.LabelProp = global::Mono.Unix.Catalog.GetString("a = ");
			this.label33.Justify = ((global::Gtk.Justification)(1));
			this.table3.Add(this.label33);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table3[this.label33]));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label34 = new global::Gtk.Label();
			this.label34.Name = "label34";
			this.label34.LabelProp = global::Mono.Unix.Catalog.GetString("b = ");
			this.label34.Justify = ((global::Gtk.Justification)(1));
			this.table3.Add(this.label34);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table3[this.label34]));
			w21.TopAttach = ((uint)(1));
			w21.BottomAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment3.Add(this.table3);
			this.frame5.Add(this.GtkAlignment3);
			this.labelFunc = new global::Gtk.Label();
			this.labelFunc.Name = "labelFunc";
			this.labelFunc.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Function Parameters</b>");
			this.labelFunc.UseMarkup = true;
			this.frame5.LabelWidget = this.labelFunc;
			this.vbox9.Add(this.frame5);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.frame5]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.frame7 = new global::Gtk.Frame();
			this.frame7.Name = "frame7";
			this.frame7.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame7.Gtk.Container+ContainerChild
			this.GtkAlignment5 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment5.Name = "GtkAlignment5";
			this.GtkAlignment5.LeftPadding = ((uint)(12));
			// Container child GtkAlignment5.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.button16 = new global::Gtk.Button();
			this.button16.CanFocus = true;
			this.button16.Name = "button16";
			this.button16.UseUnderline = true;
			this.button16.Label = global::Mono.Unix.Catalog.GetString("File:");
			this.hbox10.Add(this.button16);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.button16]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.entryFile = new global::Gtk.Entry();
			this.entryFile.CanFocus = true;
			this.entryFile.Name = "entryFile";
			this.entryFile.Text = global::Mono.Unix.Catalog.GetString("none");
			this.entryFile.IsEditable = false;
			this.entryFile.InvisibleChar = '●';
			this.hbox10.Add(this.entryFile);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.entryFile]));
			w26.Position = 1;
			this.vbox10.Add(this.hbox10);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox10]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.checkCorrel = new global::Gtk.CheckButton();
			this.checkCorrel.CanFocus = true;
			this.checkCorrel.Name = "checkCorrel";
			this.checkCorrel.Label = global::Mono.Unix.Catalog.GetString("Do Decorrelation");
			this.checkCorrel.DrawIndicator = true;
			this.checkCorrel.UseUnderline = true;
			this.vbox10.Add(this.checkCorrel);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.checkCorrel]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.checkWhite = new global::Gtk.CheckButton();
			this.checkWhite.CanFocus = true;
			this.checkWhite.Name = "checkWhite";
			this.checkWhite.Label = global::Mono.Unix.Catalog.GetString("Do Whitening");
			this.checkWhite.DrawIndicator = true;
			this.checkWhite.UseUnderline = true;
			this.vbox10.Add(this.checkWhite);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.checkWhite]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			this.GtkAlignment5.Add(this.vbox10);
			this.frame7.Add(this.GtkAlignment5);
			this.GtkLabel4 = new global::Gtk.Label();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Data</b>");
			this.GtkLabel4.UseMarkup = true;
			this.frame7.LabelWidget = this.GtkLabel4;
			this.vbox9.Add(this.frame7);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.frame7]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			this.hbox9.Add(this.vbox9);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.vbox9]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			this.vbox8.Add(this.hbox9);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox9]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			w34.Padding = ((uint)(6));
			// Container child vbox8.Gtk.Box+BoxChild
			this.frame6 = new global::Gtk.Frame();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.table4 = new global::Gtk.Table(((uint)(8)), ((uint)(2)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.hscaleConstrain = new global::Gtk.HScale(null);
			this.hscaleConstrain.CanFocus = true;
			this.hscaleConstrain.Name = "hscaleConstrain";
			this.hscaleConstrain.Adjustment.Lower = 1D;
			this.hscaleConstrain.Adjustment.Upper = 144D;
			this.hscaleConstrain.Adjustment.PageIncrement = 12D;
			this.hscaleConstrain.Adjustment.StepIncrement = 1D;
			this.hscaleConstrain.Adjustment.Value = 1D;
			this.hscaleConstrain.DrawValue = true;
			this.hscaleConstrain.Digits = 0;
			this.hscaleConstrain.ValuePos = ((global::Gtk.PositionType)(2));
			this.table4.Add(this.hscaleConstrain);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table4[this.hscaleConstrain]));
			w35.TopAttach = ((uint)(5));
			w35.BottomAttach = ((uint)(6));
			w35.LeftAttach = ((uint)(1));
			w35.RightAttach = ((uint)(2));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.hscaleCrossRatio = new global::Gtk.HScale(null);
			this.hscaleCrossRatio.CanFocus = true;
			this.hscaleCrossRatio.Name = "hscaleCrossRatio";
			this.hscaleCrossRatio.Adjustment.Upper = 1D;
			this.hscaleCrossRatio.Adjustment.PageIncrement = 0.33D;
			this.hscaleCrossRatio.Adjustment.StepIncrement = 0.01D;
			this.hscaleCrossRatio.Adjustment.Value = 0.06D;
			this.hscaleCrossRatio.DrawValue = true;
			this.hscaleCrossRatio.Digits = 2;
			this.hscaleCrossRatio.ValuePos = ((global::Gtk.PositionType)(2));
			this.table4.Add(this.hscaleCrossRatio);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table4[this.hscaleCrossRatio]));
			w36.TopAttach = ((uint)(4));
			w36.BottomAttach = ((uint)(5));
			w36.LeftAttach = ((uint)(1));
			w36.RightAttach = ((uint)(2));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.hscaleDropOut = new global::Gtk.HScale(null);
			this.hscaleDropOut.CanFocus = true;
			this.hscaleDropOut.Name = "hscaleDropOut";
			this.hscaleDropOut.Adjustment.Upper = 1D;
			this.hscaleDropOut.Adjustment.PageIncrement = 0.33D;
			this.hscaleDropOut.Adjustment.StepIncrement = 0.01D;
			this.hscaleDropOut.Adjustment.Value = 0.5D;
			this.hscaleDropOut.DrawValue = true;
			this.hscaleDropOut.Digits = 2;
			this.hscaleDropOut.ValuePos = ((global::Gtk.PositionType)(2));
			this.table4.Add(this.hscaleDropOut);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table4[this.hscaleDropOut]));
			w37.TopAttach = ((uint)(3));
			w37.BottomAttach = ((uint)(4));
			w37.LeftAttach = ((uint)(1));
			w37.RightAttach = ((uint)(2));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.hscaleLearnRate = new global::Gtk.HScale(null);
			this.hscaleLearnRate.CanFocus = true;
			this.hscaleLearnRate.Name = "hscaleLearnRate";
			this.hscaleLearnRate.Adjustment.Lower = 0.001D;
			this.hscaleLearnRate.Adjustment.Upper = 12D;
			this.hscaleLearnRate.Adjustment.PageIncrement = 3D;
			this.hscaleLearnRate.Adjustment.StepIncrement = 1D;
			this.hscaleLearnRate.Adjustment.Value = 0.12D;
			this.hscaleLearnRate.DrawValue = true;
			this.hscaleLearnRate.Digits = 3;
			this.hscaleLearnRate.ValuePos = ((global::Gtk.PositionType)(2));
			this.table4.Add(this.hscaleLearnRate);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table4[this.hscaleLearnRate]));
			w38.LeftAttach = ((uint)(1));
			w38.RightAttach = ((uint)(2));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.hscaleMomentum = new global::Gtk.HScale(null);
			this.hscaleMomentum.CanFocus = true;
			this.hscaleMomentum.Name = "hscaleMomentum";
			this.hscaleMomentum.Adjustment.Upper = 1D;
			this.hscaleMomentum.Adjustment.PageIncrement = 0.33D;
			this.hscaleMomentum.Adjustment.StepIncrement = 0.001D;
			this.hscaleMomentum.Adjustment.Value = 0.03D;
			this.hscaleMomentum.DrawValue = true;
			this.hscaleMomentum.Digits = 3;
			this.hscaleMomentum.ValuePos = ((global::Gtk.PositionType)(2));
			this.table4.Add(this.hscaleMomentum);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table4[this.hscaleMomentum]));
			w39.TopAttach = ((uint)(1));
			w39.BottomAttach = ((uint)(2));
			w39.LeftAttach = ((uint)(1));
			w39.RightAttach = ((uint)(2));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.hscaleRegular = new global::Gtk.HScale(null);
			this.hscaleRegular.CanFocus = true;
			this.hscaleRegular.Name = "hscaleRegular";
			this.hscaleRegular.Adjustment.Upper = 6D;
			this.hscaleRegular.Adjustment.PageIncrement = 1D;
			this.hscaleRegular.Adjustment.StepIncrement = 0.1D;
			this.hscaleRegular.Adjustment.Value = 0.3D;
			this.hscaleRegular.DrawValue = true;
			this.hscaleRegular.Digits = 0;
			this.hscaleRegular.ValuePos = ((global::Gtk.PositionType)(2));
			this.table4.Add(this.hscaleRegular);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table4[this.hscaleRegular]));
			w40.TopAttach = ((uint)(6));
			w40.BottomAttach = ((uint)(7));
			w40.LeftAttach = ((uint)(1));
			w40.RightAttach = ((uint)(2));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.hscaleSmartScale = new global::Gtk.HScale(null);
			this.hscaleSmartScale.CanFocus = true;
			this.hscaleSmartScale.Name = "hscaleSmartScale";
			this.hscaleSmartScale.Adjustment.Lower = 1D;
			this.hscaleSmartScale.Adjustment.Upper = 12D;
			this.hscaleSmartScale.Adjustment.PageIncrement = 1D;
			this.hscaleSmartScale.Adjustment.StepIncrement = 0.1D;
			this.hscaleSmartScale.Adjustment.Value = 1D;
			this.hscaleSmartScale.DrawValue = true;
			this.hscaleSmartScale.Digits = 0;
			this.hscaleSmartScale.ValuePos = ((global::Gtk.PositionType)(2));
			this.table4.Add(this.hscaleSmartScale);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table4[this.hscaleSmartScale]));
			w41.TopAttach = ((uint)(7));
			w41.BottomAttach = ((uint)(8));
			w41.LeftAttach = ((uint)(1));
			w41.RightAttach = ((uint)(2));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.hscaleStopDW = new global::Gtk.HScale(null);
			this.hscaleStopDW.CanFocus = true;
			this.hscaleStopDW.Name = "hscaleStopDW";
			this.hscaleStopDW.Adjustment.Lower = 0.0001D;
			this.hscaleStopDW.Adjustment.Upper = 0.3D;
			this.hscaleStopDW.Adjustment.PageIncrement = 0.1D;
			this.hscaleStopDW.Adjustment.StepIncrement = 0.0001D;
			this.hscaleStopDW.Adjustment.Value = 0.02D;
			this.hscaleStopDW.DrawValue = true;
			this.hscaleStopDW.Digits = 4;
			this.hscaleStopDW.ValuePos = ((global::Gtk.PositionType)(2));
			this.table4.Add(this.hscaleStopDW);
			global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table4[this.hscaleStopDW]));
			w42.TopAttach = ((uint)(2));
			w42.BottomAttach = ((uint)(3));
			w42.LeftAttach = ((uint)(1));
			w42.RightAttach = ((uint)(2));
			w42.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label24 = new global::Gtk.Label();
			this.label24.Name = "label24";
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString("Learn Rate:");
			this.label24.Justify = ((global::Gtk.Justification)(1));
			this.table4.Add(this.label24);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table4[this.label24]));
			w43.XOptions = ((global::Gtk.AttachOptions)(4));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label25 = new global::Gtk.Label();
			this.label25.Name = "label25";
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("Momentum:");
			this.label25.Justify = ((global::Gtk.Justification)(1));
			this.table4.Add(this.label25);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table4[this.label25]));
			w44.TopAttach = ((uint)(1));
			w44.BottomAttach = ((uint)(2));
			w44.XOptions = ((global::Gtk.AttachOptions)(4));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label26 = new global::Gtk.Label();
			this.label26.Name = "label26";
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString("Stopping dW:");
			this.table4.Add(this.label26);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table4[this.label26]));
			w45.TopAttach = ((uint)(2));
			w45.BottomAttach = ((uint)(3));
			w45.XOptions = ((global::Gtk.AttachOptions)(4));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label27 = new global::Gtk.Label();
			this.label27.Name = "label27";
			this.label27.LabelProp = global::Mono.Unix.Catalog.GetString("DropOut Probability:");
			this.label27.Justify = ((global::Gtk.Justification)(1));
			this.table4.Add(this.label27);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table4[this.label27]));
			w46.TopAttach = ((uint)(3));
			w46.BottomAttach = ((uint)(4));
			w46.XOptions = ((global::Gtk.AttachOptions)(4));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label28 = new global::Gtk.Label();
			this.label28.Name = "label28";
			this.label28.LabelProp = global::Mono.Unix.Catalog.GetString("Cross-Validation Ratio:");
			this.label28.Justify = ((global::Gtk.Justification)(1));
			this.table4.Add(this.label28);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table4[this.label28]));
			w47.TopAttach = ((uint)(4));
			w47.BottomAttach = ((uint)(5));
			w47.XOptions = ((global::Gtk.AttachOptions)(4));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label29 = new global::Gtk.Label();
			this.label29.Name = "label29";
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString("Constraining Modulo:");
			this.label29.Justify = ((global::Gtk.Justification)(1));
			this.table4.Add(this.label29);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table4[this.label29]));
			w48.TopAttach = ((uint)(5));
			w48.BottomAttach = ((uint)(6));
			w48.XOptions = ((global::Gtk.AttachOptions)(4));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label30 = new global::Gtk.Label();
			this.label30.Name = "label30";
			this.label30.LabelProp = global::Mono.Unix.Catalog.GetString("Regularization aspect:");
			this.label30.Justify = ((global::Gtk.Justification)(1));
			this.table4.Add(this.label30);
			global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.table4[this.label30]));
			w49.TopAttach = ((uint)(6));
			w49.BottomAttach = ((uint)(7));
			w49.XOptions = ((global::Gtk.AttachOptions)(4));
			w49.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label31 = new global::Gtk.Label();
			this.label31.Name = "label31";
			this.label31.LabelProp = global::Mono.Unix.Catalog.GetString("Smart Scale Factor:");
			this.label31.Justify = ((global::Gtk.Justification)(1));
			this.table4.Add(this.label31);
			global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table4[this.label31]));
			w50.TopAttach = ((uint)(7));
			w50.BottomAttach = ((uint)(8));
			w50.XOptions = ((global::Gtk.AttachOptions)(4));
			w50.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment4.Add(this.table4);
			this.frame6.Add(this.GtkAlignment4);
			this.GtkLabel3 = new global::Gtk.Label();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Learning Global Parameters</b>");
			this.GtkLabel3.UseMarkup = true;
			this.frame6.LabelWidget = this.GtkLabel3;
			this.vbox8.Add(this.frame6);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.frame6]));
			w53.PackType = ((global::Gtk.PackType)(1));
			w53.Position = 2;
			w53.Expand = false;
			w53.Fill = false;
			w1.Add(this.vbox8);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(w1[this.vbox8]));
			w54.Position = 0;
			w54.Expand = false;
			w54.Fill = false;
			// Internal child MultiPerceptron.ConfigDialog.ActionArea
			global::Gtk.HButtonBox w55 = this.ActionArea;
			w55.Name = "dialog1_ActionArea";
			w55.Spacing = 10;
			w55.BorderWidth = ((uint)(5));
			w55.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w56 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w55[this.buttonCancel]));
			w56.Expand = false;
			w56.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w57 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w55[this.buttonOk]));
			w57.Position = 1;
			w57.Expand = false;
			w57.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 1960;
			this.DefaultHeight = 1398;
			this.Show();
			this.button16.Clicked += new global::System.EventHandler(this.ButtonFile);
			this.buttonOk.Clicked += new global::System.EventHandler(this.ButtonOK);
		}
	}
}
